
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?sub ?newsub FROM <???> WHERE {
  ?sub rdf:type ?concept .
  SERVICE <http://dbpedia.org/sparql> {
    ?newsub rdf:type ?concept
  }
}